name: clip_dam
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - numpy
  - pillow
  - faiss-cpu
  - pip:
      - torch
      - torchvision
      - streamlit
      - tqdm
      - sentence-transformers
      - pymupdf
      - python-docx
      - python-pptx
      - git+https://github.com/openai/CLIP.git